on:
  workflow_dispatch:
jobs:
  build_latex:
    name: "build pdf"
    # ubuntu-slim is usually preferred, but latex-action requires docker-in-docker
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v4
        with:
          root_file: resume.tex
      - name: setup and configure gitsign
        run: |
          wget https://github.com/sigstore/gitsign/releases/download/v0.17.1/gitsign_0.17.1_linux_amd64.deb
          sudo dpkg -i gitsign_0.17.1_linux_amd64.deb
          git config --global gpg.x509.program gitsign
          git config --global gpg.format x509
          git config --global commit.gpgsign true
          git config --global tag.gpgsign true
      - name: Push new compiled resume
        env:
          GITSIGN_OIDC_MODE: ambient
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add -f resume.pdf
          git diff --staged --quiet && exit 0
          git commit -m "[gh-action] Compile Resume"
          git push origin HEAD:master

